

load("//bazel:yacl.bzl", "yacl_cc_binary")

package(default_visibility = ["//visibility:public"])

yacl_cc_binary(
    name = "ourpsi",
    srcs = [
        "main.cc",
        "malpsi.h",
        "malpsi.cc",
        "utils.h",
        "debug_logging.h",
        "local_comm_stats.h",
        "cpsi.h",
        "cpsi.cc",
        "psica.h",
        "psica.cc",
        "psisum.h",
        "psisum.cc",
        "pjc.h",
        "pjc.cc",
        "cuckoohash.h",
        "peqt.h",
        "psi.h",
        "psi.cc",
        "bokvs.h",
        "bokvs.cc",
        "uint.h",
        "volepsi/Defines.h",
        "volepsi/config.h",
        "volepsi/GMW/Circuit.h",
        "volepsi/GMW/Circuit.cpp",
        "volepsi/GMW/Gmw.h",
        "volepsi/GMW/Gmw.cpp",
        "volepsi/GMW/SilentTripleGen.h",
        "volepsi/GMW/SilentTripleGen.cpp",
    ],
    deps = [
    "//examples/otokvspsi/okvs:baxos",
    "//yacl/base:byte_container_view",
    "//yacl/base:dynamic_bitset",
    "//yacl/base:exception",
    "//yacl/kernel/algorithms:base_ot",
    "//yacl/base:int128",
    "//yacl/kernel/type:ot_store_utils",
    "//yacl/math/f2k:f2k",
    "//examples/otokvspsi/okvs:galois128",
    "//yacl/crypto/hash:blake3",
    "//yacl/utils:parallel",
    "//yacl/crypto/hash:hash_utils",
    "//yacl/crypto/rand:rand",
    "//yacl/link:context",
    "//examples/otokvspsi/bandokvs:bandokvs_lib",
    "@com_google_absl//absl/container:flat_hash_set"
    ],
    defines = [
        "LIBDIVIDE_AVX2",
    ],
    copts = [
        "-maes",
        "-mpclmul",
        "-msse2",
        "-msse3",
        "-msse4.1",
        "-mavx2",
        "-fopenmp",
        "-O3",
        "-std=c++20",
        "-march=native",
        "-mavx512f",
        "-I/usr/local/include",
        "-I/usr/local/include/securejoin/out/libOTe/thirdparty",
        "-I/usr/local/include/secure-join/out/libOTe/thirdparty",
    ],
    linkopts = [
        "-fopenmp",
        "-O3",
        "-L/usr/local/lib",
        "-Wl,--start-group",
        "-llibOTe",
        "-lSimplestOT",
        "-lKyberOT",
        "-lcryptoTools",
        "-lcoproto",
        "-Wl,--end-group",
        "-lssl",
        "-lcrypto",
        "-lsodium",
        "-ldl",
        "-pthread",
    ]
)


    
